### ISSUE TITLE
Duplicate entries while using indexing on multi server env

### ISSUE THREAD

**Issue by SourabhKhatri** [WeTeam/WeBlog#138]
I am using the latest version of blog code published on Sep 15, 2015. I have configured this with sitecore 7.0 with multi server env (separate CD and CM server). With this, i am finding duplicate entries  on blog home page, however same code is good in single server env. While i am disabling the strategies defined in weblog.contentsearch.sc70.config, this issue has resolved but it's not showing me latest entries now. Does any one has encounter this issue. I am not sure which strategies needs to keep on CD and CM servers. 

  <strategy ref="contentSearch/indexUpdateStrategies/syncMaster" />
              <strategy ref="contentSearch/indexUpdateStrategies/rebuildAfterFullPublish" />
              <strategy ref="contentSearch/indexUpdateStrategies/onPublishEndAsync" />
              <strategy ref="contentSearch/indexUpdateStrategies/remoteRebuild" />

**Comment by alan-null** [comment]
hello @SourabhKhatri,

We have got two different things here
#### WeBlog.ContentSearch.SC70.config
Are you talking about developer environment? I am asking because there is no such file in the release package.
My guess is you messed something with configs, probably duplicated some configurations by copying config from WeBlog project into website.

#### Content Delivery / Content Management
If you want to have to separate servers this is a guideline to setup it:
1. Create **wb_cm** (Content Management) instance
2. Install **[WeBlog.2.4.0.for.Sitecore.7.0.to.7.2.zip](https://github.com/WeTeam/WeBlog/releases/download/release%2F2.4/WeBlog.2.4.0.for.Sitecore.7.0.to.7.2.zip)** on **wb_cm**
3. Create **wb_cd** (Content Delivery) instance
4. Install **[WeBlog.2.4.0.for.Sitecore.7.0.to.7.2.zip](https://github.com/WeTeam/WeBlog/releases/download/release%2F2.4/WeBlog.2.4.0.for.Sitecore.7.0.to.7.2.zip)** on **wb_cd**
5. Configure CD server

The main purpose of this configuration: **WeBlog.delivery.config** is to get rid of unnecessary event handlers etc. Perfect solution for *Content Delivery* server, where you just serve content without managing it.
There is one thing you need to remember when enabling this config. You have to disable this config **WeBlog.config** (remove it from *App_Config/Include* or change the extension from **.config* to *.disabled* )

Hope it helps.

**Comment by alan-null** [comment]
Closed due to lack of activity.
