### ISSUE TITLE
Import from Wordpress does not work on Sitecore 8.0 update 7

### ISSUE THREAD

**Issue by olivier-github** [WeTeam/WeBlog#159]
The import from Wordpress does not allow to import an XML file on Sitecore 8.0 update 7.
And even you rename it with a .zip extension, the import failed.

**Comment by alan-null** [comment]
Hello @olivier-github,

Could you give us more details about your issue?

1. Make sure you file with wordpress data is uploaded into packages folder
2. Make sure it has `xml` extension, otherwise it won't be visible for file the picker.
3. If you cannot see tree while choosing blog destination install this package:
https://dl.dropboxusercontent.com/u/191345630/Stecore/WeBlog/ImportDialogFix.zip
(it will make one fragment height 90%)

If your data in xml file is well formatted, everything should go smooth. 

If you get errors during import and you don't know why I am pretty sure it will be NewsMover issue.
Workaround for this is comment out `<events>` section in `WeBlog.config` file.

I am not sure which of these issues apply to your situation.
Let me know about your results.
