### ISSUE TITLE
Why the data published not reflected on UI - Sitecore

### ISSUE THREAD

**Issue by alpasarupria** [WeTeam/WeBlog#177]

**Comment by adeneys** [comment]
With no description provided it's hard to tell what the issue might be.

But this may be related to issue #176

**Comment by JenKove** [comment]
We thought we were having this problem. It turned out that the cache settings had to be cleared on the blog sublayouts in the cacheable section, especially for the post listing. If we typed the name of the path for the published (but invisible) item, it appeared. But until we updated the cache settings, it would not appear because the pieces of the blog page that displayed new content were all blocked by the cache setting. See [this post](https://www.linkedin.com/pulse/sitecore-81-from-66-post-upgrade-tips-jennifer-rose?trk=pulse_spock-articles) to verify if this is what you are experiencing.

**Comment by alan-null** [comment]
Most recent version of the WeBlog was tested and I haven't encountered anything like that.
