### ISSUE TITLE
Wordpress Import: Can't choose import location in Chrome

### ISSUE THREAD

**Issue by techphoria414** [WeTeam/WeBlog#34]
After choosing an import file and continuing through the wizard, unable to choose an import location.

![Screen Shot 2013-04-03 at 6 11 05 PM](https://f.cloud.github.com/assets/1562106/336837/cab1052c-9cb3-11e2-98ab-c3c91d855d5c.png)

Sitecore 6.5 rev 120706. Might be a Sheer UI issue we can't do anything about. Workaround is to use Firefox.

**Comment by alan-null** [comment]
Console error:
```
Uncaught ReferenceError: showModalDialog is not defined
```
Possible solution:
- use Firefox instead of Google Chrome

Possible workaround:
- update security policy on your computer. You will find tutorial [here](http://www.bugdebugzone.com/2014/08/sitecore-modal-pop-ups-are-not-working.html)

We could rewrite this dialog with SPEAK in the near future.
