### ISSUE TITLE
Creating Multiple blogs inside one instance

### ISSUE THREAD

**Issue by Warunika** [WeTeam/WeBlog#83]
I can create two or more blogs inside one instance. But when I'm previewing the blog it will mixed up all the posts and previewing the post which are not relevant to the previewed blog. Im using WeBlog_WeBlog_SC8 version in the Content Search branch

**Comment by adeneys** [comment]
Try the beta build that was released yesterday https://github.com/WeTeam/WeBlog/blob/feature/content_search_support/data/packages/WeBlog-2.4.0_beta_sc8.0.zip . In my testing prior to releasing this build I did not witness this issue.

**Comment by alan-null** [comment]
Issue fixed. Problem no longer exists.

**Comment by cfotache** [comment]
I'm experiencing the same issue, using 2.3.0 now.
I tried downloading the 2.4.0 beta but the link above is broken. Where could I download that (for Sitecore 8), or another version where there would be no issues with multiple blogs?

**Comment by alan-null** [comment]
Hi @cfotache,
You will find all public releases [here](https://github.com/WeTeam/WeBlog/releases)

**Comment by cfotache** [comment]
We found one single issue when having 2 instances. The PostListEntry.ascx control isn't part of the Presentation, instead it's called directly from PostList, so we can't pick a duplicate version to style it differently in the second instance. Is there any way around it?

**Comment by alan-null** [comment]
Hi @cfotache 

You can assign different **PostListEntry.ascx** file per **PostList** rendering using its rendering parameters. 
There is a rendering parameter called: **PostTemplate** under *Customization* section.
If not set, default value will be taken
```csharp
DEFAULT_POST_TEMPLATE = "/layouts/WeBlog/PostListEntry.ascx";
```

p.s
I think it should solve your problem, the only one problem I can see now is that you are not able to change standard values of the category item (you can, but you are not able to have 2 different sv), thus each category item will have to be edited manually once you create new one to change the post template.

hope it helps.

**Comment by cfotache** [comment]
@alan-null Thank you for your help so far!
Having another issue now, hope it's the last one. On the 2nd instance, it shows the entries with the correct PostTemplate that we set in the Customization section. However, when we click "View more", it loads the additional entries with the (different) Default_Post_Template. Any suggestion on what's wrong? Thanks!

**Comment by alan-null** [comment]
Hello @cfotache 

Everything is under control.
WeBlog uses separate device and layout to load entries dynamically via java script.

You just have to change the **PostTemplate** in one more place.
Open you Blog Root presentation details and find device **WeBlog AJAX** and change the **Post Template** in **PostList** component. (see image below)
![image](https://cloud.githubusercontent.com/assets/6848691/12424155/1d276608-becf-11e5-9e33-b9a4bd7fc7cc.png)

**Comment by cfotache** [comment]
@alan-null Thanks, that worked perfectly. Now I think I'm stuck with the final bottleneck:
For the entry page, I can have the same template in both blogs, however the presentation controls are different (as they were on the main page). I can't think of any way of separating the template presentation between the 2 instances, so when I add entries to the first blog, they have one layout, and the second blog has a different one. Any suggestion how this can be solved?

**Comment by alan-null** [comment]
@cfotache As WeBlog does not support multiple templates per single Sitecore instance yet it is not possible out of the box (multi-template support is another big thing we want to implement).

### My idea to solve it is:
#### What you already have :
**BlogEntry** - this is standard WeBlog Entry template

#### What you need:
**BlogEntryVariant1** - this will be custom template
* use **BlogEntry** as a base template
* create Standard Values for new template and override presentation details 

**BlogEntryVariant2** - this will be custom template 
* use **BlogEntry** as a base template
* create Standard Values for new template and override presentation details

**Some code:**
Create event handler for event **item:created**. 
More details about Sitecore events [here](https://sdn.sitecore.net/Articles/API/Using%20Events.aspx)

Check if created item derive from **BlogEntry** template and it is not **BlogEntry** template at the same time (which means we will catch only 'variant' templates). Then change its template to **BlogEntry** template. (if you have already WeBlog dll referenced, you can use ``WeBlog.Settings.EntryTemplateID`` in order to get template ID)

After you have all the things, just change your **blog1** and **blog2** insert options, using **BlogEntryVariant1** or **BlogEntryVariant2**.

Using this trick you should end up with the same **BlogEntry** template based entries but different presentation details.

I didn't test this solution, I've made something similar but I changed the template using Workflow action.
Let me know about the results. If something is not clear do not hesitate to ask.
