### ISSUE TITLE
Localized month names in folders?

### ISSUE THREAD

**Issue by noxhoej** [WeTeam/WeBlog#85]
Is there any way to specify the Culture/locale/Language used for generating month names, when using the default MonthTemplate of
```xml
<MonthTemplate formatString="MMMM">Common/Folder</MonthTemplate>
```
such that you would get e.g. `2015/februar` instead of `2015/February` in the 'da-DK' locale? Preferably configurable per blog or per site...

**Comment by alan-null** [comment]
Hi Nicholas,

This feature comes from **NewsMover** module, not **WeBlog**.

CultureInfo is taken from your machine, without any option to change it.
You can see how it is implemented here:
https://github.com/JimmieOverby/NewsMover/blob/master/Tasks/Folder.cs#L50

You have got following options:
* Change in *WeBlog.config*  the date format for the month from **"MMMM"** to **"%M"** - this will give you numbers instead of text for months names. This is the fastest method, but I don't know if you accept month numbers instead of names
* Fork NewsMover project and append changes by yourself by setting explicit culture info in the code
```csharp
        public static string GetName(DateTime date)
        {
            CultureInfo cultureInfo = new CultureInfo("da-DK");
            return date.ToString(FormatString, cultureInfo);
        }
```
* Step above can be extended with configuration file if you want to make it less "hardcoded". Add extra property to the Folder model:
https://github.com/JimmieOverby/NewsMover/blob/master/Tasks/Folder.cs#L34
and read value from config file defined like that.
```xml
<MonthTemplate formatString="MMMM" cultureInfoName="da-DK">Common/Folder</MonthTemplate>
```

None of the solutions proposed above will let you set the format per site or per blog. they are global (per Sitecore instance). 

Hope it helps

**Comment by adeneys** [comment]
If you're using Sitecore 7 or above you can use Item Buckets instead of NewsMover. So we don't globber the entire site and Item Bucket behaviour WeBlog includes a `DynamicBucketFolderPathSelector` to allow defining different folder structures per bucket. We also include the `SimpleCreationDateBucketFolderPath` class to create the date folder structure in the bucket. You could create your own class implementing `IDynamicBucketFolderPath` and customize it to use the month names as you require.
